-- Arsip akhir semester (templat). BACA DULU sebelum menjalankan.
--
-- Kebijakan: data peserta disimpan sampai akhir semester, lalu diarsipkan.
-- Urutan yang aman:
--   1. Unduh rekap (CSV) dari dashboard atau lewat Table Editor > Export.
--   2. Ekspor tabel penting ke berkas (Supabase > Database > Backups, atau pg_dump).
--   3. Setelah arsip tersimpan di tempat lain dan sudah diperiksa, barulah hapus.
--
-- Perintah di bawah BERSIFAT MERUSAK dan tidak bisa dibatalkan. Dibiarkan sebagai
-- komentar. Hapus tanda komentar hanya setelah langkah 1 dan 2 selesai.

-- Contoh: hapus riwayat percobaan dan aktivitas, simpan progres dan laporan.
-- delete from public.percobaan;      -- termasuk pola dan rekaman cara menulis
-- delete from public.aktivitas;
-- delete from public.sesi_perangkat;  -- catatan perangkat yang dipakai masuk
-- delete from public.perangkat_bersama;
-- delete from public.sesi_belajar;       -- jam dan lama aktif belajar (kehadiran dan keaktifan)
-- delete from public.koreksi_kehadiran;  -- koreksi manual kehadiran
-- Jadwal (jadwal_kelas, jadwal_riwayat) boleh disimpan atau dihapus sesuai kebutuhan.
-- Untuk penelitian: ekspor dulu data anonim dari tab Riset (CSV atau JSON beserta kamus data) dan simpan di tempat aman,
-- baru hapus percobaan di atas. Kunci pemetaan kode_riset ke peserta ada di kolom profiles.kode_riset; hapus kunci itu
-- (update public.profiles set kode_riset = null, riset_setuju = null;) bila datanya tidak perlu bisa ditelusuri lagi.
-- delete from public.riset_ekspor_log;

-- Contoh: hapus seluruh data peserta semester ini (akun, progres, laporan, unggahan).
-- Berkas di Storage ('tugas') harus dihapus terpisah lewat dashboard Storage.
-- delete from auth.users where id in (select id from public.profiles where peran = 'peserta');
